# Integration tests CodeBuild
version: 0.2
phases:
  install:
    commands:
      - n 16.15
      - cd packages/integration-tests
#      - npm ci
  build:
    commands:
      - bash ./codebuild-run-tests.sh
artifacts:
  files:
    - integration-tests/**/*
